### ISSUE TITLE
extract some variables to be configurable in Emacs-side

### ISSUE THREAD

**Issue by it-is-wednesday** [it-is-wednesday/pyinspect.el#7]
- _pyinspect_ITEM_CAP
- _pyinspect_STR_CAP

**Comment by jgarte** [comment]
Hi, could you elaborate further on why this would be useful? I might be missing context to understanding what those do

**Comment by it-is-wednesday** [comment]
Those are the default values for [`_pyinspect_trim`](https://github.com/it-is-wednesday/pyinspect.el/blob/main/pyinspect.py#L53), but this function will probably be obsolete after reimplementing pyinspect in hierarchy.el. By the way, thanks for the interest you took in this project!
